### ISSUE TITLE
Crash and error

### ISSUE THREAD

**Issue by Eragonfr** [traverseda/PyCraft#87]
Traceback (most recent call last): File "/usr/local/bin/pycraft", line 11, in <module> load_entry_point('pycraft==0.1.0', 'console_scripts', 'pycraft')() File "/usr/local/lib/python3.5/dist-packages/pycraft-0.1.0-py3.5.egg/pycraft/main.py", line 28, in main pyglet.app.run() File "/usr/local/lib/python3.5/dist-packages/pyglet/app/__init__.py", line 143, in run event_loop.run() File "/usr/local/lib/python3.5/dist-packages/pyglet/app/base.py", line 136, in run self._run_estimated() File "/usr/local/lib/python3.5/dist-packages/pyglet/app/base.py", line 165, in _run_estimated timeout = self.idle() File "/usr/local/lib/python3.5/dist-packages/pyglet/app/base.py", line 274, in idle redraw_all = self.clock.call_scheduled_functions(dt) File "/usr/local/lib/python3.5/dist-packages/pyglet/clock.py", line 309, in call_scheduled_functions item.func(ts - item.last_ts, *item.args, **item.kwargs) File "/usr/local/lib/python3.5/dist-packages/pycraft-0.1.0-py3.5.egg/pycraft/window.py", line 127, in update self.gamestatemanager.peek().update(dt, self.ticks_per_second) File "/usr/local/lib/python3.5/dist-packages/pycraft-0.1.0-py3.5.egg/pycraft/gs_running.py", line 148, in update self.world.process_queue(ticks_per_second) File "/usr/local/lib/python3.5/dist-packages/pycraft-0.1.0-py3.5.egg/pycraft/world/world.py", line 172, in process_queue self._dequeue() File "/usr/local/lib/python3.5/dist-packages/pycraft-0.1.0-py3.5.egg/pycraft/world/world.py", line 160, in _dequeue self._show_block(coords, self.area.get_block(coords)) File "/usr/local/lib/python3.5/dist-packages/pycraft-0.1.0-py3.5.egg/pycraft/world/area.py", line 57, in get_block return self.blocks[coords] if self.blocks[coords] else None KeyError: (134, -1, -131)

**Comment by zhengxyz123** [comment]
> I'm poor in English, using Chinese can make you understand what I want to say more quickly

我看到过相同的错误, 但不是在这个项目中, 是我的一个 Minecraft 克隆, 这个问题已经得到了修复. 

这个错误告诉你的是: 没有在 (134, -1, -131) 处的这个方块. 可能你破坏了这个方块, 又再次破坏它.

我知道这个不可能, 但是确实发生过, 我也不太清楚为什么, 这个很有可能是一个 bug.

**Comment by Eragonfr** [comment]
I just don't think it's worth to fix this, it is a random bug, and the project does not seems to be updated anyways.
